### ISSUE TITLE
OME-NGFF samples data

### ISSUE THREAD

**Issue by jburel** [ome/ome-ngff-tools#13]
Collection of urls pointing to public data 
We can then decide where that collection should be presented

* https://idr.github.io/ome-ngff-samples/
* https://uk1s3.embassy.ebi.ac.uk/bia-zarr-test/bia_examples.html
* https://s3.embl.de/i2k-2020/platy-raw.ome.zarr (https://s3.embl.de/i2k-2020)
* https://zenodo.org/record/7120354#.Y2ziK-zP1Oc
* https://webknossos.org/datasets/scalable_minds/l4dense_motta_et_al_demo#2924,4474,1770,0,3.4
* Links to consider in https://hackmd.io/@ome/HJq5cSNV5

**Comment by jburel** [comment]
See also https://github.com/ome/ome-ngff-validator/issues/17

**Comment by joshmoore** [comment]
See also https://github.com/ome/ngff/issues/140 which was shared during the meeting.

**Comment by jburel** [comment]
https://forum.image.sc/t/data-streaming-with-webknossos-libs/73702 for usage of webknossos-libs

**Comment by jburel** [comment]
Closing in favour of https://github.com/ome/ngff/issues/140
